kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ .Release.Name }}-bot
  namespace: {{ .Release.Namespace }}
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template: 
        spec:
          serviceAccountName: {{ .Release.Name }}-ingress-controller-service-account
          volumes:
            - name: {{ .Release.Name }}-bot-config
              configMap:
                name: {{ .Release.Name }}-bot-config
                defaultMode: 420
          containers:
            - name: {{ .Release.Name }}-bot
              image: alpine
              env: 
                - name: TAG
                  value: {{ .Values.config.tag }}
                - name: REPO
                  value: {{ .Values.config.repo }}
                - name: CERTIFICATEFOLDER
                  value: {{ .Values.bundle.repo }}
                - name: CONFIG_MAP
                  value: {{ .Values.config.map }}
                - name: CONFIG_NAMESPACE
                  value: {{ .Release.Namespace }}
                - name: BUNDLE_NAMESPACE
                  value: {{ .Release.Namespace }}
                - name: BUNDLE_NAME
                  value: {{ .Release.Name }}-{{ .Values.bundle.name }}
                - name: SEPERATOR
                  value: {{ .Values.config.seperator | quote }}
                - name: INGRESS_NAME
                  value: {{ .Values.ingress.name }}
                - name: INGRESS_NAMESPACE
                  value: {{ .Values.ingress.namespace }}
              args:
                - /bin/sh
                - /tmp/script.sh
              resources: {}
              volumeMounts:
                - name: {{ .Release.Name }}-bot-config
                  mountPath: /tmp
              imagePullPolicy: Always
          restartPolicy: Never
