apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-ingress-rule-role
rules:
  - apiGroups:
      [
        "",
        "apps",
        "rbac.authorization.k8s.io",
        "roles.rbac.authorization.k8s.io",
        "authorization.k8s.io",
        "networking.k8s.io",
        "networking.k8s.io/v1",
        "extensions",
      ]
    resources: ["ingresses"]
    resourceNames: [{{ .Values.ingress.name }}]
    verbs: ["get", "watch", "list", "create", "delete", "patch"]
